# Generated by Django 5.1.6 on 2025-02-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
