# Generated by Django 5.1.6 on 2025-02-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0003_client_is_verified_freelancer_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingprojects',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ongoingprojects',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
