# Generated by Django 5.1.6 on 2025-02-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0004_ongoingprojects_end_date_ongoingprojects_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectquote',
            name='advance_payment',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='ongoingprojects',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ongoingprojects',
            name='start_date',
            field=models.DateField(),
        ),
    ]
