# Generated by Django 5.1.6 on 2025-02-21 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0006_milestones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestones',
            name='ongpId',
        ),
        migrations.AddField(
            model_name='milestones',
            name='bid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='milestones_model', to='db_schemas.projectquote'),
            preserve_default=False,
        ),
    ]
