# Generated by Django 5.1.6 on 2025-02-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0007_remove_milestones_ongpid_milestones_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestones',
            name='amount',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
