# Generated by Django 5.1.6 on 2025-02-22 13:29

import db_schemas.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0008_alter_milestones_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('taskId', models.CharField(default=db_schemas.models.generate_task_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('title', models.DateField()),
                ('status', models.CharField(default='Requirement Gathering', max_length=20)),
                ('isChecked', models.BooleanField(default=False)),
                ('comments', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taskBid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_model', to='db_schemas.projectquote')),
            ],
        ),
    ]
