# Generated by Django 5.1.6 on 2025-02-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0010_alter_tasks_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(default='Requirement Gathering', max_length=50),
        ),
    ]
