# Generated by Django 5.1.6 on 2025-02-27 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0012_alter_myadmin_password_alter_myadmin_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectquote',
            name='admin',
            field=models.ForeignKey(default='AD001', on_delete=django.db.models.deletion.CASCADE, to='db_schemas.myadmin'),
        ),
    ]
