# Generated by Django 5.1.6 on 2025-02-27 12:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0013_projectquote_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=12)),
                ('logo_name', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
