# Generated by Django 5.1.6 on 2025-02-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0014_partnerlogos'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPageAdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField()),
                ('media_type', models.CharField()),
                ('media_name', models.CharField()),
                ('media_url', models.URLField()),
                ('reduirect_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
