# Generated by Django 5.1.6 on 2025-02-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0015_jobpageadv'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsPageAdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(blank=True, null=True)),
                ('section_name', models.CharField(blank=True, null=True)),
                ('media_type', models.CharField(blank=True, null=True)),
                ('media_name', models.CharField(blank=True, null=True)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('reduirect_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='JobPageAdv',
        ),
    ]
