# Generated by Django 5.1.6 on 2025-02-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0016_jobspageadv_delete_jobpageadv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobspageadv',
            old_name='reduirect_link',
            new_name='redirect_link',
        ),
    ]
