# Generated by Django 5.1.6 on 2025-02-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0017_rename_reduirect_link_jobspageadv_redirect_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsPageImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(blank=True, null=True)),
                ('media_type', models.CharField(blank=True, null=True)),
                ('media_name', models.CharField(blank=True, null=True)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(blank=True, null=True)),
                ('media_type', models.CharField(blank=True, null=True)),
                ('media_name', models.CharField(blank=True, null=True)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('anc_text', models.CharField(blank=True, max_length=225, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
