# Generated by Django 5.1.6 on 2025-03-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0018_jobspageimages_webannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingprojects',
            name='msg_comments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
