# Generated by Django 5.1.6 on 2025-03-04 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0019_ongoingprojects_msg_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectquote',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_schemas.myadmin'),
        ),
    ]
