# Generated by Django 5.1.6 on 2025-03-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0020_alter_projectquote_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectquote',
            name='admin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
