# Generated by Django 5.1.6 on 2025-03-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0021_alter_projectquote_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectquote',
            old_name='admin',
            new_name='admin_id',
        ),
    ]
