# Generated by Django 5.1.6 on 2025-03-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0022_rename_admin_projectquote_admin_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectStatusDetails',
        ),
    ]
