# Generated by Django 5.1.6 on 2025-03-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schemas', '0023_delete_projectstatusdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='profilePic',
            field=models.ImageField(blank=True, default='https://gigzera-s3-bkt.s3.ap-south-1.amazonaws.com/clients/profile_sample.jpeg', null=True, upload_to='client/profile_pics/'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='profilePic',
            field=models.ImageField(blank=True, default='https://gigzera-s3-bkt.s3.ap-south-1.amazonaws.com/freelancers/profile_sample.jpeg', null=True, upload_to='freelancer/profile_pics/'),
        ),
        migrations.AlterField(
            model_name='partnerlogos',
            name='logo_url',
            field=models.URLField(),
        ),
    ]
